# Generated by Django 3.1 on 2020-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='date_edited')),
            ],
            options={
                'verbose_name': 'MainSlider',
                'verbose_name_plural': 'MainSliders',
            },
        ),
    ]
